### ISSUE TITLE
The system shall be able to send critical alert notifications from the remote site to the Ordering Provider.

### ISSUE THREAD

**Issue by VikkiM** [VHAINNOVATIONS/RemoteOrdering#14]
Provide the ability where the system is able to send critical alerts notification from the remote site to the Ordering Provider.

**Comment by mjgaynor** [comment]
from Allison Amrhein on 12/8/2015

There may be some logistical problems to find the patient urgently to treat; for instance, the remote provider may not know the current circumstances of the patient as well as the home VA does (for instance, patient may be having appointments outside the VA through the Choice Act and may not be able to be found urgently.)
