### ISSUE TITLE
SharePoint for Document Management

### ISSUE THREAD

**Issue by VikkiM** [VHAINNOVATIONS/RemoteOrdering#17]
As a Scrum Team member, I need to see all the documents in a central repository.

**Comment by VikkiM** [comment]
Vikki and Abbie have access to the new wiki but still need to get documents uploaded.

**Comment by amobley** [comment]
SharePoint has been established; leaving item open until all users have access.

**Comment by AzulJunge** [comment]
Any ETA associated with SharePoint accounts on the horizon? ;-)

**Comment by amobley** [comment]
@AzulJunge my token didn't arrive yet, so I plan on going into the office tomorrow to create user accounts for non-Leidos folks. I have to be on the company network to do that.

**Comment by amobley** [comment]
Added users with E-IDE accounts to the SharePoint site. Updated contacts list. Researching workflows.

**Comment by AzulJunge** [comment]
Thank you, Allison.  Let's see what we will see.

**Comment by AzulJunge** [comment]
Ooops!!  Sorry, Abbie.  Got my "A's" mixed up.

**Comment by amobley** [comment]
@VikkiM to check on E-IDI account for @JCSMnjenkins and make sure there's an email associate with it.

**Comment by VikkiM** [comment]
The Q1IM system keeps hanging once I save his email. If I can't get through, I'll call the help desk.

**Comment by VikkiM** [comment]
oops, reopening

**Comment by amobley** [comment]
@VikkiM and I are working on Nintex Workflow design to allow customer to approve deliverables on SharePoint

**Comment by VikkiM** [comment]
Let's close this issue since we established the document repository, and open a new issue for creating the approval workflow.
