### ISSUE TITLE
All Scrum Team members are part of the Remote Ordering team

### ISSUE THREAD

**Issue by VikkiM** [VHAINNOVATIONS/RemoteOrdering#19]
As Scrum Master, I need all team members to show up as "watching" this "RemoteOrdering" repository so that they can add issues and be assigned to issues.

**Comment by VikkiM** [comment]
11/12 ... still missing Kevin Stoddard (developer). He has not see the confirmation email from GitHub for his user name Azul....

**Comment by bciv** [comment]
Resent invitation from GitHub to AzulJunge (Kevin).

**Comment by VikkiM** [comment]
Thank you

**Comment by VikkiM** [comment]
The initial team has access to GitHub.
