### ISSUE TITLE
System Design Document (SDD)

### ISSUE THREAD

**Issue by VikkiM** [VHAINNOVATIONS/RemoteOrdering#25]

**Comment by N-Ram** [comment]
SDD provided and updated

**Comment by N-Ram** [comment]
Reviewed the document, Incorporated the  Architectural diagrams that were created and updated by Kevin into SDD.  It is working document.

**Comment by mjgaynor** [comment]
Sprint 4 SDD
General updates to Sections 1 & 2
Added figure to Section 4.4
Removed architecture and design elements that have not been finalized
Technical edit

**Comment by amobley** [comment]
Performed technical edit and checked back into SharePoint.

**Comment by mjgaynor** [comment]
Sprint 5 SDD
Updated diagrams and added content globally

**Comment by mjgaynor** [comment]
Sprint 6 SDD
Updated Table 9 and 57
Updated Figure 7
Updated sections 4.4, 6.2.1.1.4, 6.2.2.3.33, 6.5

**Comment by mjgaynor** [comment]
Sprint 7 SDD
Performed technical edit
Updated Figure 7

**Comment by mjgaynor** [comment]
Sprint 8 SDD
Performed technical edit
Updated 3.2.3.1.1, 6.2.2.3.17, 6.2.2.3.18, 6.2.12, 6.5
Added 3.2.3.1.2.
Updated Tables 32, 35-40
Updated Figure 8
Added Figures 9-11

**Comment by mjgaynor** [comment]
Sprint 9 SDD
No updates

**Comment by mjgaynor** [comment]
Sprint 10 SDD
Updated Figure 4

**Comment by mjgaynor** [comment]
Sprint 11 SDD
Inserted Figure 1

**Comment by mjgaynor** [comment]
Sprint 12 SDD
No Updates

**Comment by mjgaynor** [comment]
Sprint 13 SDD
No Updates

**Comment by mjgaynor** [comment]
Sprint 14 SDD
No Updates

**Comment by mjgaynor** [comment]
Sprint 15 SDD
Updated Figure 5 & Figure 9
Moved Section 6.5 content to Section 9 (Appendix A)
Updated sections, 3.3.3, 4.4 & 6.2.2.3.33

**Comment by mjgaynor** [comment]
Sprint 16 SDD
No Updates

**Comment by amobley** [comment]
Update to SDD
10/21/2016
