### ISSUE TITLE
Determine how we view the results from all sites

### ISSUE THREAD

**Issue by VikkiM** [VHAINNOVATIONS/RemoteOrdering#28]
Necessary for validating that results are in.

Anyone should be able to view it in VistA.

Figure it out and then update the diagram.

The diagram currently considers using XML. Cache comes with XML classes already defined; it's just a matter of creating instances and utilizing those. Cache puts results in a local database. Will need middleware to access the remote results. 

Kevin: Lots of options to consider.

**Comment by AzulJunge** [comment]
This approach has been scrapped.
