### ISSUE TITLE
Master Test Plan & Test Cases

### ISSUE THREAD

**Issue by N-Ram** [VHAINNOVATIONS/RemoteOrdering#31]

**Comment by srinivasakanumetta** [comment]
Sprint 4 Master Test Plan

**Comment by mjgaynor** [comment]
Sprint 5 Test Cases provided
• Updated TC-1
• Added TC-2, -3, -4, -5, -6 & -7

Sprint 5 Master Test Plan provided

**Comment by mjgaynor** [comment]
Sprint 6 
Test Cases
Minor Updates

Sprint 6 Master Test Plan
• Updated sections 1.3, 1.4, 2, 5.2 & 8.3
• Minor updates

**Comment by mjgaynor** [comment]
Sprint 7 Test Cases
Updated TC-1, -4, -6

Sprint 7 Master Test Plan
• Updated sections 8.1 and 8.2

**Comment by mjgaynor** [comment]
Sprint 8 Test Cases
Updated TC-6
Added TC1.1, TC-8

Sprint 8 Master Test Plan
Updated sections 2.2, 2.4, 4.5, 7, 8.1, 8.2 and 8.3

**Comment by mjgaynor** [comment]
Sprint 9 Test Cases
Renumbered Test Cases, TC3 changed to TC5, TC4 to TC3, TC5 to TC6, TC6 to TC4, TC7 to TC20
Added TC6.1, TC6.2, TC6.3, TC6.4, TC6.5, TC7, TC7.1
Minor updates 

Sprint 9 Master Test Plan
Updated sections 2.3 and 8.1

**Comment by mjgaynor** [comment]
Sprint 10 Test Cases
Updated TC-5.1, TC-7, TC-7.1
Revised Section TC-6 and added additional test scripts
Added Appendix A

Sprint 10 Master Test Plan
Minor Updates

**Comment by mjgaynor** [comment]
Sprint 11 Test Cases
Updated TC-5.1, TC-6.4, TC-6.7, Appendix
Added TC-5.2, TC-7.2, TC-7.3, TC-8, TC-8.1, TC-8.2, TC-8.3

Sprint 11 Master Test Plan
Updated sections 1.4, 2.3, 2.5 and 3.4

**Comment by mjgaynor** [comment]
Sprint 12 Test Cases
Added TC-8.4, TC-8.5, TC-8.6, TC-8.7, TC-8.8
Removed TC-30

Sprint 12 Master Test Plan
Minor updates to section 2.3, 2.5, 4.5

**Comment by Ilustrisimo** [comment]
Sprint 13 Test Cases
Added Panel Test Cases to Section TC-7 (Lab Accessioning)
Minor Updates to Test Cases in Section TC-8 (Lab Resulting)

Sprint 13 Master Test Plan
Minor updates to multiple sections

**Comment by mjgaynor** [comment]
Sprint 14 Master Test Plan
No Updates

**Comment by mjgaynor** [comment]
Sprint 15 Master Test Plan
Updates to Sections 2.0 and 2.4
Added Appendix Information for the eMI Broker
Replaced SQA Environment Diagram 
Minor Updates

**Comment by mjgaynor** [comment]
Sprint 16 Master Test Plan
Updated with latest testing information

**Comment by amobley** [comment]
August 2016 update, final delivery version
