### ISSUE TITLE
The system shall establish a secure connection to VA sites for exchange of patient Identity information  by following VA standards for privacy. 

### ISSUE THREAD

**Issue by mjgaynor** [VHAINNOVATIONS/RemoteOrdering#32]

**Comment by VikkiM** [comment]
Per conversation with Paul DeSantis (1/14/16): This feature is out of scope. There is a known vulnerability for TCP/IP in HL7 messaging. Whatever security is in place for the VistA HL7 subscriber links will be maintained for this prototype.
