### ISSUE TITLE
Acronym list

### ISSUE THREAD

**Issue by VikkiM** [VHAINNOVATIONS/RemoteOrdering#39]
Create a list of acronyms used on this project and post on GitHub site under the reference Pipeline (ZenHub) and in the SharePoint document repository.

**Comment by amobley** [comment]
Reviewing existing VA acronym list for relevance and completeness--will upload final version.

**Comment by amobley** [comment]
Project glossary has been uploaded to the SOTTP SharePoint as a reference document. Will update this doc with more terms as we develop other deliverables.
