### ISSUE TITLE
The Ordering Provider shall be able to enter lab and radiology orders for a remote site using CPRS.

### ISSUE THREAD

**Issue by VikkiM** [VHAINNOVATIONS/RemoteOrdering#4]
As a product owner, I want to build functionality where the ordering provider is able to enter lab and radiology orders for a VA patient from a local site such as CPRS.

**Comment by VikkiM** [comment]
Since this is the sprint 4 goal, let's keep it in Sprint 4 until Sprint 4 is complete. If this feature is incomplete at the Sprint Review, we will move it to Sprint 5. I understand that we are only working part of this feature for Sprint 4.

**Comment by mjgaynor** [comment]
[SOTTP US 1-1 Order a Lab Test at a Remote Site.docx](https://github.com/VHAINNOVATIONS/RemoteOrdering/files/74029/SOTTP.US.1-1.Order.a.Lab.Test.at.a.Remote.Site.docx)

[SOTTP US 1-2 Retain Previous Site Value on Order Lab Test Form.docx](https://github.com/VHAINNOVATIONS/RemoteOrdering/files/74030/SOTTP.US.1-2.Retain.Previous.Site.Value.on.Order.Lab.Test.Form.docx)

**Comment by VikkiM** [comment]
Next step for Feature #4 is to complete the user stories via elaboration session for ordering radiology tests at remote sites and retain previous site value on Radiology Test.

**Comment by VikkiM** [comment]
Remaining items for lab ordering functionality:
1) implement dynamic approach to selecting remote sites from a drop-down list that can be automatically populated from a database vs. hard-coded
2) associated GUI updates
3) repeat above for radiology
