### ISSUE TITLE
Duplicate Order Message when Changing the Lab Location

### ISSUE THREAD

**Issue by mjgaynor** [VHAINNOVATIONS/RemoteOrdering#85]
If the user creates an order, saves it, changes it and then saves it again, they get a Duplicate Order message.  There is no other order in the system for the user.  

Is this the correct behavior?  

This is occurring in the Sandbox environment.

**Comment by tckehoe1** [comment]
Yes it is correct.  You ordered two tests.  One original and then you changed it so the changed test is a second test.  You’re supposed to get that error.  It is an attempt to stop the providers from ordering duplicate tests for the same patient….some of these tests are very expensive.
